---
-
  #make sure we can do passwordless sudoers
  #*************************************************
  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'

  - name: Add sudoers users to wheel group
    user: name=deployer groups=wheel append=yes state=present createhome=yes
  #********************************************************
  #users and groups
  - name: Add user group
    group: name={{item}} state=present
    with_items: "{{admin_users}}"

  - name: create users
    user: name={{item}} shell=/bin/bash groups={{item}},sudo,wheel
    with_items: "{{admin_users}}"

  #keys -  user key
    #create key with ssh-keygen -t rsa -b 4096
  - name: Add ssh key to users
    authorized_key: user={{item}} key="{{ lookup('file', 'keys/{{item}}.pub') }}"
    with_items: "{{admin_users}}"
