---

songscape_repo        : https://github.com/andre-geldenhuis/songscape
songscape_install_dir : /opt/songscape
intermediate_data_dir : /kiwi
snippets_data_dir     : /www/media
test_data_dir         : /opt/test_data

wavy_repo             : https://github.com/dragonfly-science/numpy-wavy
wavy_install_dir      : /opt/wavy

db_name               : halosounds
db_user               : songscape
db_password           : "{{ lookup('password', 'secret_key_db length=35') }}"

app_secret_key        : "{{ lookup('password', 'secret_key_app length=35') }}"
app_allowed_hosts     : ".dragonfly.co.nz"
browserid_audiences   : https://songscape-staging.dragonfly.co.nz
